version: '3.8'

services:
  postgres_second:
    image: postgres:15
    container_name: odoo_postgres_second
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo2
      - POSTGRES_PASSWORD=odoo2
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data-second:/var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"  # Changed to 5433 to avoid conflict
    networks:
      - odoo_network_second
    restart: unless-stopped

volumes:
  odoo-db-data-second:
    name: odoo-db-data-second

networks:
  odoo_network_second:
    name: odoo_network_second